[package]
name = "math_lib"
version = "0.1.0"
authors = ["Chloe Holmes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "math_lib"
path = "src/lib.rs"

[[bin]]
name = "math_bin"
path = "src/bin.rs"